### ISSUE TITLE
Expand heating control mode options

### ISSUE THREAD

**Issue by bsileo** [bsileo/SmartThings_Pentair#10]
And while I am on a roll - the heat settings need 4 discrete options:
0. Off
Heater
Solar Preferred
Solar Only
For both Spa and Pool

**Comment by bsileo** [comment]
@donkarnag Do you know what the correct command are to send to poolControl for SolarPreferred and SolarOnly heat options?

**Comment by bsileo** [comment]
Ok this is fixed in the latest code @donkarnag. I can not test as I do not have this equipment so take a look. I see it fine all the way to the poolController so I think OK.

**Comment by donkarnag** [comment]
@bsileo<mailto:reply@reply.github.com> I have some of the values written down at home but am traveling this week.  Also trying to decipher the valve values, which seem to defy logic.  I will send what I have when I get home, and check the merged code.  Thanks!
