### ISSUE TITLE
Look into adding support for hostnames instead of IP addresses

### ISSUE THREAD

**Issue by bsileo** [bsileo/SmartThings_Pentair#14]

**Comment by bsileo** [comment]
A possibility to solve this:
https://community.smartthings.com/t/convert-hostname-to-ip-address/9860/18

**Comment by arrmo** [comment]
This is for an Internet resolvable IP address ... no? Rather, use nslookup on the nodejs-poolController machine?

**Comment by bsileo** [comment]
We have IP addresses needs on both PoolController and within the ST app.  Both could ptoentially be resolved from FQDNs I suppose.  I think the typical setup is all lan-lan using private non-routable addresses for the poolController and the ST Hub.

**Comment by arrmo** [comment]
Yep, that makes sense! I was just meaning that the link above goes to the internet to resolve the name, right? That won't work for internal (non-routable) addresses ... so rather use local DNS, which should go upstream if needed.

Thoughts?

**Comment by bsileo** [comment]
Yes local DNS would be ideal but I think its a matter of finding a way to do that from within the ST environment.

**Comment by arrmo** [comment]
Agreed! Thinking server / client here ... meaning provide this capability on the local LAN via nodejs-poolController (API), or another port / server type of call ... then connect from ST get the info. Will try to take a look at this - first debugging why I can see state now in My Home, but not inside Pentair.

Thanks!

**Comment by bsileo** [comment]
Of course the problem with that idea is you need to find the poolController
first to ask it for DNS services. Another option that fits with ST
architecture is to use UPNP to discover the poolController and configure
the device properly. You could then have the ST environment pass over its
IP address to it for use in socket.io integration back to ST.  The firts
half looks to be possible if we added a UPNP client to the poolController
node server.

But, I am questioning if it is worth all this effort versus having the
installer just enter these IP addresses? There are many other reasons why
only a pretty technical user can install this solution anyway so manually
entering IPs is not a big step

> --

Brad Sileo

412.498.8602

**Comment by bsileo** [comment]
Closing this - it has been made irrelevant with the use of SSDP as the ST side now automatically finds the right IP/Port for the poolController.
