### ISSUE TITLE
Implement support for SSDP/ UPNP and SmartApp discovery model

### ISSUE THREAD

**Issue by bsileo** [bsileo/SmartThings_Pentair#17]

**Comment by bsileo** [comment]
Initial capability is setup in dev code. Need to sort out support for SSDP alongside PoolController to make this automatic instead of manual entry of the IP/Post/Mac to find it.

@tagyoureit thoughts on adding a SSDP server to poolController to allow HA equipment to find it?

**Comment by tagyoureit** [comment]
This should be working now with the latest push.

**Comment by bsileo** [comment]
This is all in place - just need to update Readme
