### ISSUE TITLE
Config return from poolController.

### ISSUE THREAD

**Issue by tagyoureit** [bsileo/SmartThings_Pentair#20]
I assembled a new endpoint `/config` that could return something like:
```
{
"intellicom": 0,
"intellitouch": 1,
"nonLightCircuits": {
"1": {
"circuitName": "SPA"
},
"2": {
"circuitName": "JETS"
},
"3": {
"circuitName": "AIR BLOWER"
},
"4": {
"circuitName": "CLEANER"
},
"5": {
"circuitName": "WATERFALL MEDIUM LOW"
},
"6": {
"circuitName": "POOL"
},
"10": {
"circuitName": "NOT USED"
},
"11": {
"circuitName": "SPILLWAY"
},
"12": {
"circuitName": "WATERFALL LOW"
},
"13": {
"circuitName": "WATERFALL MEDIUM"
},
"14": {
"circuitName": "WATERFALL HIGH"
},
"15": {
"circuitName": "POOL LOW"
},
"16": {
"circuitName": "NOT USED"
},
"17": {
"circuitName": "NOT USED"
},
"18": {
"circuitName": "NOT USED"
},
"19": {
"circuitName": "NOT USED"
},
"20": {
"circuitName": "AUX EXTRA"
}
},
"lightCircuits": {
"7": {
"circuitName": "SPA LIGHT"
},
"8": {
"circuitName": "POOL LIGHT"
},
"9": {
"circuitName": "PATH LIGHTS"
}
},`
"chlorinator": 1,
"pumps": 2,
"intellichem": 0,
"spa": 1,
"solar": 1,
"systemReady": 1  
}
```

Basically, this should allow a quick setup of items by a 3rd party (like ST).  
1. Do we need the `circuitName` or can that be retrieved later?
1. `systemReady` is a very basic check if the poolController app has all the info (if this is 0, discard until it is returned as 1).
1. In general, 0 means not installed, 1+ is installed (pumps=2 would be 2 pumps).

Thoughts?

**Comment by bsileo** [comment]
Is this in the latest 4.x-dev? I am not seeing it.  I think it is OK to get the circuitName later as I think any system out there will allow setting device name dynamically..  I think this will work well for a start for me. I need to think about getting a set of default icons for some possible types...lights, cleaner, waterfall, pumps at a minimum.

**Comment by tagyoureit** [comment]
I have it locally, but need to finish it up.  I've been distracted trying to port my light controller app to SmartThings the last few days.  :)

**Comment by bsileo** [comment]
No worries I will hold on setting up the App config code until you are
ready to bounce it over. Let me know if you hit any snags on ST side...it
really is just an ugly environment to develop in so don't think you are
missing anything!

> --

Brad Sileo

412.498.8602

**Comment by bsileo** [comment]
Note - consider using a nice set of default icons when building circuits base don the config and certain typical names.

**Comment by tagyoureit** [comment]
Yes, sort of, kind of.  The `/config` does summarize a bit, but agree there is quite a bit of overlap.
