### ISSUE TITLE
Find a way to tailor the UI to the specific configuration of the pool

### ISSUE THREAD

**Issue by bsileo** [bsileo/SmartThings_Pentair#3]
Need to be able to hide individual circuits
Show/hide  Chlor and Chem depending if they are present
Add/remove Spa
Hide solar Temp

This can be partly accomplished by deleting the child devices but that makes a mess of the remaining UI layout.

**Comment by donkarnag** [comment]
FYI - I just spend quite a while trying to figure out if we can hide tiles or sections - it is not looking good.  See this: [https://community.smartthings.com/t/dynamic-label-using-settings-on-standardtile/49186](url)

**Comment by donkarnag** [comment]
And - I have a first version of the Intellichem device handler and edits to your main Controller type.  How should I best share them with you?

**Comment by donkarnag** [comment]
Random notes to follow up on:
1. How is the 'Recently' tab populated - right now it only shows Temp updates - can we update others?
2. How can we add some basic labels to the tiles (it seems to be harder than I would think)
3. I would like to be able to export some of the values we are getting from the Controller, however there is no capability like "ORP".  How to use existing capabilities to meet ST structure... (This should go back in the other issue).

**Comment by donkarnag** [comment]
And while I am on a roll - the heat settings need 4 discrete options:
0. Off
1. Heater
2. Solar Preferred
3. Solar Only
For both Spa and Pool

**Comment by bsileo** [comment]
For the code, I am fine if you want to update in git and send me a pull request. Also Ok to make new issues here for others ideas and I'll take a look or you can!

**Comment by bsileo** [comment]
Tile labeling I can look at may be able to do some with multiattribute tiles.  Note that for the circuits you can change the icons which then show up in the main controller. Just go find them in your things list.

**Comment by bsileo** [comment]
I updated the event "Displayed" settings throughout in the repo @donkarnag so if you update your ST code you should now see more of the events on the "Recently" tab with better descriptions for some.

**Comment by bsileo** [comment]
My current thinking on UI configuration is to somewhat control this by adding/removing child devices. if we keep the UI built in sections that are multiples of 6 units on the UI, then when you remove a child all these tiles disappear and the UI could still look OK.  All the other code needs to be resilient for when a child does not exist but that is not a bad practice anyway. I have started to look at some options around this in configuration.  If you progress on the Intelichem side keep this in mind @donkarnag - look for a multiple of 6 units in the UI tiles.

**Comment by donkarnag** [comment]
Thanks.  I had already removed the Chlorinator child to bump the Intellichem sections up, and that seems to work fine, though I guess that would have to happen during installation or manually later?  
Thanks for updating the Displayed setting - I will continue that through as well.

The intellichem updates are decently stable.  I will continue to update a few things, especially translating code to English (e.g. mode 32 -> Mixing) but I might not have time to do so for another week or so.  You are welcome to take what I have from under my fork.

**Comment by donkarnag** [comment]
(and forgive my lack of git manners - this form of collaboration is new to me -  I assume that is the easiest way, but happy to do something else if better)

**Comment by bsileo** [comment]
Git is new to me too so no worries there..like finding / and looking at your fork will be a new experience for me!

**Comment by rflemming** [comment]
There may be a tip here:

https://github.com/tagyoureit/nodejs-poolController/issues/53#issuecomment-347751588

I'd try to offload all of the "what hardware do I have logic" to the controller side of things.  The end result being that the "/all" api call only returns info for what is configured.  Then on the smartthings side you can build your child devices off of that.  It already looks like it works this way for the chlorinator since I have it disabled and I'm not seeing anything about it in the output of "/all".  Getting a toggle for spa should be pretty easy and it sounds like there is a way to handle it for circuits via "Not Used"

**Comment by bsileo** [comment]
Finished a first pass at this with some preferences and adjusting the UI so it still "works" when you delete individual child devices. one big gap is you can not delete a child device form the parent device after initial creation. I may go ahead and build a parent Smartapp to try to manage this in the ST-approved manner.   But it does work right if you manually delete the devices (and set the preferences) from the IDE to get to a setup that matches your configuration.

**Comment by bsileo** [comment]
Also @donkarnag I did merge all the Intelichem changes into my master branch.  I ended up doing this manually as trying to work it through github was causing me some serious confusion. I had conflicting changes on my side etc so I just worked through it.  It is all working for me now so if you fetch the latest you should be able to see it all.

**Comment by bsileo** [comment]
Closing this issue I think we have everything here in place or have moved other items to new separate issues.
