### ISSUE TITLE
MissingMethodException (Groovy)

### ISSUE THREAD

**Issue by arrmo** [bsileo/SmartThings_Pentair#31]
From the ST / Groovy Live Log,
`error groovy.lang.MissingMethodException: No signature of method: script_dth_fd6e66d0364a804d208adb2f8cb42e81310eef4071ab6b4ee6f7881e1966bb6f.updateDataValue() is applicable for argument types: (java.lang.String, groovy.json.internal.LazyMap) values: [lightCircuits, [3:[circuitName:POOL LIGHT], 4:[circuitName:SPA LIGHT]]]`

Thanks!

**Comment by bsileo** [comment]
Corrected this...removed some code trying to save Data since this data type is not supported.
