### ISSUE TITLE
SmartThings icons and ActionTiles tiles status updates

### ISSUE THREAD

**Issue by GoodyGizmos** [bsileo/SmartThings_Pentair#35]
Does this work with Action Tiles?

**Comment by afgoody** [comment]
Now that I have things mostly working, I was able to add the SmartThings devices to ActionTiles. Here's a screenshot:
![actiontilespentair](https://user-images.githubusercontent.com/46235745/52104787-feb85880-25a0-11e9-940e-c732a3343126.JPG)
Everything works great except turning the heater on/off and changing the set point. I need to investigate that and it's why they're off to the side. If anyone has any idea why they're not working, please let me know.

**Comment by afgoody** [comment]
It appears that ActionTiles are kind of working. I don't think the DTH sends out updates when the device state is changed from another app or device (e.g. ScreenLogic iOS app, another instance of ActionTiles, etc.). Could this be added to the DTH code?

https://support.actiontiles.com/communities/12/topics/1091-switch-tile-is-not-updating-when-activated-from-another-devicealexa

**Comment by afgoody** [comment]
Additionally, I just turned on my Pool Vacuum circuit in the ST Pool Controller. The icon turned green, the pool pump turned on, and the vacuum started moving, but the Pool icon did not turn green to indicate the pump was on. I dragged down to refresh the ST Pool Controller page and the Pool Vacuum icon changed to off. I went to the Pool Vacuum child device and it was off. I checked the nodejs-poolController Control Center webpage and the Pool Vacuum circuit shows on. The entire time, the pool vacuum circuit (and pool pump) have been on. Is there a chance I've misconfigured the DTH and/or SmartApp?

**Comment by bsileo** [comment]
There are some dependencies on updates coming back form the NJS-PoolController in various parts of the code. This is because it is an asynchronous call requesting to make a change, so we then wait for the update to come back. In a similar fashion, we are subscribed to updates from the controller for changes initiated elsewhere. If these do not come the SmartThings side will not refresh as it does not do any polling right now. If you hit the refresh button on the main Pool-Controller device does it get to correct values?

**Comment by afgoody** [comment]
I’ll have to check when I reset my RPi. I tried to enable logging on it to troubleshoot disconnect issues and broke nodejs.

**Comment by afgoody** [comment]
I'm back up and running. When I tap refresh, the settings and status of the child devices all appear to refresh properly. For the original point of this issue, do you think Nodejs-poolController v6 will allow you to address those state changes more timely?

**Comment by bsileo** [comment]
Yes it is possible that some additional status info in the API may help
with this. In reality though, we may need to stick to waiting until the
physical system confirms an action back on the bus to show it has changed
status. I know there is some real lag in my Pentair system sometimes.

**Comment by bsileo** [comment]
Just FYI - The new version has a whole new approach to processing events coming form the backend nodejs-PoolController. It should greatly improve the reliability of status information in SmartThings.  You will have to redo all the ActionTiles unfortunately - I had to create all new device types to build the new version as the underlying model for the pool Controller changed a good bit.
