### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by afgoody** [bsileo/SmartThings_Pentair#37]
Any idea why the pool controller icons look like this?

Specifically...

- The Pool circuit icon is missing (it is assigned in the child device)
- The Spa circuit icon is stretched out strange (I don't think I should even have a dedicated Spa Pump device since my Screenlogic setup only has one pump
- Both of the heater icons are different
- The ambient air temperature is not a circle

![image](https://user-images.githubusercontent.com/46235745/52159856-dd1da680-265e-11e9-9eb1-d5dcbc9b5ff7.png)

Instead of this...
![image](https://user-images.githubusercontent.com/46235745/52159865-2241d880-265f-11e9-929f-df98dc3a63db.png)

**Comment by bsileo** [comment]
What type of device are you running the SmartThings app on to get these problems? I suspect it is something device specific and most likely not something that can be addressed in this specific app code.

**Comment by afgoody** [comment]
iPhone 6s

**Comment by afgoody** [comment]
After reconfiguring my RPi and reinstalling your code, the icons are still displayed strangely (like the first screenshot above) on my iPhone 6s. I'll just stick to ActionTiles though which your integration helps me with. Thank you.

**Comment by bsileo** [comment]
Ok thanks for the update.
