### ISSUE TITLE
setup finds nodejs-poolcontroller instance in the logs, but not in ST app?

### ISSUE THREAD

**Issue by johnny2678** [bsileo/SmartThings_Pentair#38]
Hi @bsileo - thanks for this.  Was all working fine until I rebuilt my rPi setup to add battery backup and solder some loose connections.

I have poolController up and running again, but when I try and run setup in the ST app, it just spins on device discovery.  Tried removing all DHT and app code and re-pull from github, but same results.

Here's my config.json:
```
        "outputToSmartThings": 1
    },
    "outputToSmartThings": {
        "address": "*",
        "port": "39500"
    },

```

and here's what the app output is in live logging:
```
be9557fe-6f2e-4a5f-80e4-cb6c142e3e98  6:50:32 PM: debug SENDING HubAction: GET /device HTTP/1.1 
HOST: 192.168.X.X:3000 

be9557fe-6f2e-4a5f-80e4-cb6c142e3e98  6:50:32 PM: info Verify UPNP PoolController Device @ http://192.168.X.X:3000/device
be9557fe-6f2e-4a5f-80e4-cb6c142e3e98  6:50:32 PM: debug DevDisc [:]
```

So it's discovering my rPi running pool controller correctly @ 192.168.X.X, just not letting me select it in setup.  Setup still says `Select a device (0 found)`

I'm sure this is something noobish, but I can't seem to figure it out.  Does anything pop out at you?

Thanks!

**Comment by johnny2678** [comment]
24 hours did the trick ;)  Tried again tonight and it worked. Closing.

**Comment by bsileo** [comment]
Great thanks got to it before I even had a chance to look

**Comment by kuestess** [comment]
@bsileo I had the same issue.  Adding the IP address of the Smartthings hub in my config.json fixed it.  Before that, it would find the nodejs-poolcontroller but seemingly never get the xml back from the /devices call.

**Comment by bsileo** [comment]
Did you get the same sequence in your logs @kuestess

**Comment by kuestess** [comment]
@bsileo Yes, same sequence as above.  Put the URL in my browser and get the XML back as expected.  Don't know much about SSDP, but perhaps Smartthings has changed something on their end?

**Comment by bsileo** [comment]
Ok I will see if I can reproduce that issue. Agreed there is a good chance of a change within Smart Things....

**Comment by therapcat** [comment]
I'm having this same issue. Is the solution to just wait 24 hours? I've hardcoded the ST hub into my config.json on the pool controller. log shows that the output to Smartthings is enabled and working.

**Comment by bsileo** [comment]
I'd recommend moving to the latest version of the code at this point. I need to update this Repo to reflect that - latest code is now housed (here)[https://github.com/bsileo/hubitat_poolcontroller]

I have not been having any trouble with the discovery on the latest codebase with SmartThings.
