### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tagyoureit** [bsileo/SmartThings_Pentair#39]
Can you remove this section since I include it with the main app: 
`Copy the outputToSmartThings.js into the integrations directory`

And also the example config file below could be cleaned up slightly like this:
```
    "integrations": {
        "outputToSmartThings": 1
    },
    "outputToSmartThings": {
        "address": "*",
        "port": "39500",
        "logEnabled": 0
    },
```

Thanks!

**Comment by bsileo** [comment]
Updated!
