### ISSUE TITLE
Use ST Capabilities for ORP, pH, etc

### ISSUE THREAD

**Issue by donkarnag** [bsileo/SmartThings_Pentair#4]
I would like to be able to export some of the values we are getting from the Controller, however there is no capability like "ORP".  How to use existing capabilities to meet ST structure, like is there a generic one?  Power meter maybe can be reused?  Can we make a new Capability?

**Comment by bsileo** [comment]
There is one for PH - [PH Capability](http://docs.smartthings.com/en/latest/capabilities-reference.html#ph-measurement)

**Comment by bsileo** [comment]
There is also this "generic" looking one call [Sensor](http://docs.smartthings.com/en/latest/capabilities-reference.html#sensor) which i used for the Salt level on the Chlorinator.
