### ISSUE TITLE
Autoname?

### ISSUE THREAD

**Issue by rsissons** [bsileo/SmartThings_Pentair#40]
"You cna also go to the Pol COntroler settings, enable Autoname, and hit Refresh to name them all from your PoolController. "

Where in ST is this done? I Don't see Autoname anywhere in the settings.

**Comment by tagyoureit** [comment]
If I remember correctly, this is on the "Pentair Pool Controller" device.  Hit the configure button in SmartThings app and I believe it's there.  Don't want to uninstall and try again to see if I'm correct.  :(
