### ISSUE TITLE
Cleanup Light function - generic button and mapping to a given circuit for on/off

### ISSUE THREAD

**Issue by bsileo** [bsileo/SmartThings_Pentair#8]
Consider removing the light-specific button and just use a generic circuit button which can be setup by the user for the light.

If so, need to work out what to do with the Main tile - Perhaps allow a user configurable mapping for this to light, pool or spa?

**Comment by tagyoureit** [comment]
One thing I did with the Siri/Homebridge integration was use a switch icon for any pool circuits and a lights witch icon for any lights.  That at least separated it out a bit.

This is what I used to see if the function is a light: ` if (['intellibrite', 'light', 'sam light', 'sal light', 'color wheel'].indexOf(circuitFunction) >= 0) {...`

**Comment by bsileo** [comment]
Partially resolved - Intellibrite lights are now handled as their own separate light type switch.
